app:
  name: spike
  env: dev
  component: backend
replicaCount: 1
image:
  repository: ghcr.io/BacktotheBone/argocd-lab-apps/spike/backend
  digest: "sha256:1d9f77b258e8b51eb7dbaa3dab423d2fecdf51c85b78ba22a3090d31416b95cb"
imagePullSecrets:
  - name: ghcr-pull
containerPort: 8080
service:
  port: 80
ingress:
  enabled: true
  className: traefik
  host: dev.spike.local
  annotations: {}
  paths:
    - path: /api
      pathType: Prefix
env:
  - name: ASPNETCORE_URLS
    value: "http://+:8080"
