app:
  name: spike
  env: dev
  component: backend
replicaCount: 1
image:
  repository: ghcr.io/BacktotheBone/argocd-lab-apps/spike/backend
  digest: "sha256:4827f33cdaf8a66c2cad7200244843efe5ca33986beff5a996090f87949ed7fd"
imagePullSecrets:
  - name: ghcr-pull
containerPort: 8080
service:
  port: 80
ingress:
  enabled: true
  className: traefik
  host: dev.spike.local
  annotations: {}
  paths:
    - path: /api
      pathType: Prefix
env:
  - name: ASPNETCORE_URLS
    value: "http://+:8080"
