name: ci-backend

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "app-scm-examples/spike/backend/**"
  pull_request:
    paths:
      - "app-scm-examples/spike/backend/**"

concurrency:
  group: dev-digest-update-backend-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/BacktotheBone/argocd-lab-apps/spike/backend
          tags: |
            type=sha,format=long

      - uses: docker/setup-qemu-action@v3
      
      - id: build
        uses: docker/build-push-action@v6
        with:
            context: ./app-scm-examples/spike/backend/
            file: ./app-scm-examples/spike/backend/Dockerfile
            push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            platforms: linux/amd64  # linux/arm64,
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Update deploy/backend/values-dev.yaml with digest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          DIGEST="${{ steps.build.outputs.digest }}"
          echo "Digest=$DIGEST"
          sudo apt-get update && sudo apt-get install -y jq
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          yq -i ".image.digest = \"$DIGEST\"" app-scm-examples/spike/deploy/backend/values-dev.yaml

      - name: Commit changes (dev auto-deploy)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if git diff --quiet; then
            echo "No changes"
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add app-scm-examples/spike/deploy/backend/values-dev.yaml
          git commit -m "ci: update backend dev image digest"
          git pull --rebase origin main
          git push origin HEAD:main
          