app:
  name: spike
  env: dev
  component: frontend
replicaCount: 1
image:
  repository: ghcr.io/BacktotheBone/argocd-lab-apps/spike/frontend
  digest: "sha256:db03af8e5e689399e87ff852691686a0866549894f02d8504385db9fab8c8c8a" # CI rellenará sha256:...
imagePullSecrets:
  - name: ghcr-pull
containerPort: 80
service:
  port: 80
ingress:
  enabled: true
  className: traefik
  host: dev.spike.local
  annotations: {}
  paths:
    - path: /
      pathType: Prefix
env: []
